kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-mini-app
  labels:
    app: my-mini-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-mini-app
  template:
    metadata:
      name: my-mini-app
      labels:
        app: my-mini-app
    spec:
      containers:
        - name: my-testapp-nginx
          image: docker.io/aleksandrovsp/aleksandrov-my-miniapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-mini-app-service
  labels:
    app: my-mini-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-mini-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: aleksandrov.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-mini-app-service
            port:
              number: 80