$ANSIBLE_VAULT;1.1;AES256
63623064346639336231383936323632636634383334346166633964646339326535313463623038
3962666338333961303037613761653864323034313262610a353830366263653466643362656162
66646564396231306332326564646135376265333836303238306437316335376634613165623062
6439336131333334660a393531393038346434353033386339323764653866633235333830626337
63633736343830666331353939353837363562653134353930353666363265613233
