name: Terraform deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - '2_main/*'
  
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy infrastructure'
        type: boolean
        default: false
        required: false
      apply:
        description: 'Apply infrastructure changes'
        type: boolean
        default: false
        required: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.YC_TOKEN }}
      AWS_ENDPOINT_URL_S3: "https://storage.yandexcloud.net"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_VMS_SSH_ROOT_KEY }}
      TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
      TF_VAR_iam_token: ${{ secrets.TF_VAR_IAM_TOKEN }}
      AWS_EC2_METADATA_DISABLED: "true"

    steps:

    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.8.4"
        
    #- name: Terraform Init
    #  run: terraform -chdir=./2_main init
    - name: Terraform Init (explicit credentials)
      run: |
        echo "Initializing Terraform with explicit backend config..."
        
        terraform -chdir=./2_main init -input=false -reconfigure \
          -backend-config="access_key=${{ secrets.YC_STORAGE_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.YC_STORAGE_SECRET_KEY }}" \
          -backend-config="endpoints={s3=\"https://storage.yandexcloud.net\"}" \
          -backend-config="region=ru-central1" \
          -backend-config="bucket=private-tfstate" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="skip_region_validation=true" \
          -backend-config="skip_credentials_validation=true" \
          -backend-config="skip_requesting_account_id=true" \
          -backend-config="skip_s3_checksum=true" \
          -backend-config="skip_metadata_api_check=true" \
          -backend-config="use_path_style=true"

    - name: Terraform Validate
      run: terraform -chdir=./2_main validate
      
    - name: Terraform Plan
      id: plan
      run: |
        terraform -chdir=./2_main plan -input=false -out=tfplan
      continue-on-error: true

    - name: Terraform Apply (Push Trigger)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.plan.outcome == 'success'
      run: terraform -chdir=./2_main apply -input=false -auto-approve tfplan

    - name: Terraform Apply (Manual Trigger)
      if: github.event_name == 'workflow_dispatch' && inputs.apply == 'true' && steps.plan.outcome == 'success'
      run: terraform -chdir=./2_main apply -input=false -auto-approve tfplan

    - name: Terraform Destroy (Manual Trigger)
      if: github.event_name == 'workflow_dispatch' && inputs.destroy == 'true'
      run: terraform -chdir=./2_main destroy -auto-approve

    - name: Check for kubeconfig
      id: check_kubeconfig
      run: |
        if [ -f "./2_main/kubeconfig/config" ]; then
          echo "kubeconfig found"
          echo "::set-output name=exists::true"
        else
          echo "kubeconfig not found"
          echo "::set-output name=exists::false"
        fi

    - name: Upload kubeconfig artifact
      if: steps.check_kubeconfig.outputs.exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: kubeconfig
        path: ./2_main/kubeconfig/config
        retention-days: 1
