name: Terraform deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - '2_main/*'
  
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        type: choice
        options:
          - apply
          - destroy
          - plan-only
        default: 'plan-only'
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: TF_VAR

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_vms_ssh_root_key: ${{ secrets.TF_VAR_VMS_SSH_ROOT_KEY }}
      ssh_root_key: ${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}
      TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
      TF_VAR_iam_token: ${{ secrets.TF_VAR_IAM_TOKEN }}
      TF_VAR_root_user_pass: ${{ secrets.TF_VAR_ROOT_USER_PASS }}

    steps:    
    - name: Save SSH key to file
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        printf '%s\n' "$ssh_root_key" > ~/.ssh/id_ed25519
        sed -i -e '/^$/d' ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    
        # Проверяем, что файл не пустой
        if [ ! -s ~/.ssh/id_ed25519 ]; then
          echo "ERROR: SSH key file is empty!"
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.8.4"
    
    - name: Terraform Init
      run: terraform -chdir=./2_main init

    - name: Terraform Validate
      run: terraform -chdir=./2_main validate
      
    - name: Terraform Plan
      id: plan
      run: |
        terraform -chdir=./2_main plan -input=false -out=tfplan

    - name: Execute Terraform Action
      run: |
        cd ./2_main
        
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "Auto-applying changes from push to main."
          terraform apply -input=false -auto-approve tfplan
        
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          case "${{ inputs.action }}" in
            "apply")
              echo "Manually applying changes."
              terraform apply -input=false -auto-approve tfplan
              ;;
            "destroy")
              echo "Destroying infrastructure."
              terraform destroy -auto-approve
              ;;
            "plan-only")
              echo "Showing plan only."
              terraform show -no-color tfplan
              ;;
          esac
        fi

    - name: Check for kubeconfig
      id: check_kubeconfig
      run: |
        if [ -f "./2_main/ansible-config-k8s-cluster/.artifact/config" ]; then
          echo "kubeconfig found"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "kubeconfig not found"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload kubeconfig artifact
      if: steps.check_kubeconfig.outputs.exists == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: kubeconfig
        path: ./2_main/ansible-config-k8s-cluster/.artifact/config
        retention-days: 1

